//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAutoClient.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareAutovehicule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AdaugareAutovehicule(string marca, string model, string an_fabricatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareAutovehicule", ReplyAction="*")]
        System.Threading.Tasks.Task AdaugareAutovehiculeAsync(string marca, string model, string an_fabricatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareTipuriReparatii", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AdaugareTipuriReparatii(string denumire_reparatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareTipuriReparatii", ReplyAction="*")]
        System.Threading.Tasks.Task AdaugareTipuriReparatiiAsync(string denumire_reparatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareReparatiiEfectuate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AdaugareReparatiiEfectuate(string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugareReparatiiEfectuate", ReplyAction="*")]
        System.Threading.Tasks.Task AdaugareReparatiiEfectuateAsync(string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareAutovehicule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ModificareAutovehicule(string cod_auto, string marca, string model, string an_fabricatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareAutovehicule", ReplyAction="*")]
        System.Threading.Tasks.Task ModificareAutovehiculeAsync(string cod_auto, string marca, string model, string an_fabricatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareTipuriReparatii", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ModificareTipuriReparatii(string cod_reparatie, string denumire_reparatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareTipuriReparatii", ReplyAction="*")]
        System.Threading.Tasks.Task ModificareTipuriReparatiiAsync(string cod_reparatie, string denumire_reparatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareReparatiiEfectuate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ModificareReparatiiEfectuate(string nr_crt, string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificareReparatiiEfectuate", ReplyAction="*")]
        System.Threading.Tasks.Task ModificareReparatiiEfectuateAsync(string nr_crt, string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereAutovehicule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StergereAutovehicule(string cod_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereAutovehicule", ReplyAction="*")]
        System.Threading.Tasks.Task StergereAutovehiculeAsync(string cod_auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereTipuriReparatii", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StergereTipuriReparatii(string cod_reparatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereTipuriReparatii", ReplyAction="*")]
        System.Threading.Tasks.Task StergereTipuriReparatiiAsync(string cod_reparatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereReparatiiEfectuate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StergereReparatiiEfectuate(string nr_crt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergereReparatiiEfectuate", ReplyAction="*")]
        System.Threading.Tasks.Task StergereReparatiiEfectuateAsync(string nr_crt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfisAutovehicule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AfisAutovehicule();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfisAutovehicule", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AfisAutovehiculeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfisTipuriReparatii", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AfisTipuriReparatii();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfisTipuriReparatii", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AfisTipuriReparatiiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfisReparatiiEfectuate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AfisReparatiiEfectuate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfisReparatiiEfectuate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> AfisReparatiiEfectuateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ServiceAutoClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceAutoClient.ServiceReference1.WebService1Soap>, ServiceAutoClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AdaugareAutovehicule(string marca, string model, string an_fabricatie) {
            base.Channel.AdaugareAutovehicule(marca, model, an_fabricatie);
        }
        
        public System.Threading.Tasks.Task AdaugareAutovehiculeAsync(string marca, string model, string an_fabricatie) {
            return base.Channel.AdaugareAutovehiculeAsync(marca, model, an_fabricatie);
        }
        
        public void AdaugareTipuriReparatii(string denumire_reparatie) {
            base.Channel.AdaugareTipuriReparatii(denumire_reparatie);
        }
        
        public System.Threading.Tasks.Task AdaugareTipuriReparatiiAsync(string denumire_reparatie) {
            return base.Channel.AdaugareTipuriReparatiiAsync(denumire_reparatie);
        }
        
        public void AdaugareReparatiiEfectuate(string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare) {
            base.Channel.AdaugareReparatiiEfectuate(cod_reparatie, cod_auto, durata_efectuare, data_finalizare);
        }
        
        public System.Threading.Tasks.Task AdaugareReparatiiEfectuateAsync(string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare) {
            return base.Channel.AdaugareReparatiiEfectuateAsync(cod_reparatie, cod_auto, durata_efectuare, data_finalizare);
        }
        
        public void ModificareAutovehicule(string cod_auto, string marca, string model, string an_fabricatie) {
            base.Channel.ModificareAutovehicule(cod_auto, marca, model, an_fabricatie);
        }
        
        public System.Threading.Tasks.Task ModificareAutovehiculeAsync(string cod_auto, string marca, string model, string an_fabricatie) {
            return base.Channel.ModificareAutovehiculeAsync(cod_auto, marca, model, an_fabricatie);
        }
        
        public void ModificareTipuriReparatii(string cod_reparatie, string denumire_reparatie) {
            base.Channel.ModificareTipuriReparatii(cod_reparatie, denumire_reparatie);
        }
        
        public System.Threading.Tasks.Task ModificareTipuriReparatiiAsync(string cod_reparatie, string denumire_reparatie) {
            return base.Channel.ModificareTipuriReparatiiAsync(cod_reparatie, denumire_reparatie);
        }
        
        public void ModificareReparatiiEfectuate(string nr_crt, string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare) {
            base.Channel.ModificareReparatiiEfectuate(nr_crt, cod_reparatie, cod_auto, durata_efectuare, data_finalizare);
        }
        
        public System.Threading.Tasks.Task ModificareReparatiiEfectuateAsync(string nr_crt, string cod_reparatie, string cod_auto, string durata_efectuare, string data_finalizare) {
            return base.Channel.ModificareReparatiiEfectuateAsync(nr_crt, cod_reparatie, cod_auto, durata_efectuare, data_finalizare);
        }
        
        public void StergereAutovehicule(string cod_auto) {
            base.Channel.StergereAutovehicule(cod_auto);
        }
        
        public System.Threading.Tasks.Task StergereAutovehiculeAsync(string cod_auto) {
            return base.Channel.StergereAutovehiculeAsync(cod_auto);
        }
        
        public void StergereTipuriReparatii(string cod_reparatie) {
            base.Channel.StergereTipuriReparatii(cod_reparatie);
        }
        
        public System.Threading.Tasks.Task StergereTipuriReparatiiAsync(string cod_reparatie) {
            return base.Channel.StergereTipuriReparatiiAsync(cod_reparatie);
        }
        
        public void StergereReparatiiEfectuate(string nr_crt) {
            base.Channel.StergereReparatiiEfectuate(nr_crt);
        }
        
        public System.Threading.Tasks.Task StergereReparatiiEfectuateAsync(string nr_crt) {
            return base.Channel.StergereReparatiiEfectuateAsync(nr_crt);
        }
        
        public System.Data.DataSet AfisAutovehicule() {
            return base.Channel.AfisAutovehicule();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AfisAutovehiculeAsync() {
            return base.Channel.AfisAutovehiculeAsync();
        }
        
        public System.Data.DataSet AfisTipuriReparatii() {
            return base.Channel.AfisTipuriReparatii();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AfisTipuriReparatiiAsync() {
            return base.Channel.AfisTipuriReparatiiAsync();
        }
        
        public System.Data.DataSet AfisReparatiiEfectuate() {
            return base.Channel.AfisReparatiiEfectuate();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AfisReparatiiEfectuateAsync() {
            return base.Channel.AfisReparatiiEfectuateAsync();
        }
    }
}
